name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate Commands JSON structure
      run: node ./internal/validate-commands-json.js
    
    - name: Validate Commands
      run: node ./internal/validate-commands.js